apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cattle-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-rancher-ingress
  namespace: cattle-system
spec:
  dnsNames:
    - rancher.local # Ajuste se mudar o host
  secretName: tls-rancher-ingress
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer